"""initial schema

Hand-written (not autogenerated) — no live Postgres instance was available to
autogenerate against during implementation. Written to match
app/repositories/orm_models.py exactly; regenerate/diff via
`uv run alembic revision --autogenerate -m "check drift"` against a real
Postgres instance and hand-review before trusting this in production, per
the Phase 6 plan's migration review checklist (ADR-0021).

Revision ID: 14db6c81d4f0
Revises:
Create Date: 2026-07-15
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14db6c81d4f0"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agreements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("agreement_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("facility_amount", sa.Numeric(asdecimal=True), nullable=False),
        sa.Column("facility_type", sa.String(), nullable=False),
        sa.Column("borrower_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "lender_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False
        ),
        sa.Column("facility_agent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("interest_terms", postgresql.JSONB(), nullable=False),
        sa.Column("repayment_schedule", postgresql.JSONB(), nullable=False),
        sa.Column("covenants", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("base_status", sa.String(), nullable=False),
    )

    op.create_table(
        "covenant_test_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "agreement_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agreements.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # No FK to a covenant: covenants live in agreements.covenants (JSONB),
        # not their own table — intentional, pre-existing gap, see ADR-0021.
        sa.Column("covenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("test_date", sa.Date(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("tested_by", sa.String(), nullable=False),
    )

    op.create_table(
        "default_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "agreement_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agreements.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("occurred_date", sa.Date(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("related_covenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("related_external_reference", sa.String(), nullable=True),
        sa.Column("remediation_status", sa.String(), nullable=False),
        sa.Column("waiver_status", sa.String(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("default_events")
    op.drop_table("covenant_test_results")
    op.drop_table("agreements")
